# ============================
# APPLICATION
# ============================
spring.application.name=Freelix
server.port=8080

# ============================
# DATABASE - SQLite
# ============================
spring.datasource.url=jdbc:sqlite:freelix.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# ============================
# JPA / HIBERNATE
# ============================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# ============================
# THYMELEAF
# ============================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ============================
# FILE UPLOAD
# ============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# ============================
# CLOUDINARY
# ============================
cloudinary.cloud-name=dmpdjklk8
cloudinary.api-key=326348868831558
cloudinary.api-secret=G0z4mWLqwokGdLkcUsiZEf_QDBU

# ============================
# LOGGING
# ============================
logging.level.com.freelix=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
